### PR TITLE
remove runtime poetry dep, add pip check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

notes:
- thanks for maintaining this!
- removes `poetry` from `run` dependencies, as per [upstream](https://github.com/jdb78/lipo/blob/master/pyproject.toml#L41-L45)
- adds `pip check` to see if other potential issues are still present in this, or its dependencies...

I was a little surprised to see poetry end up in an environment, and eventually figured out it was coming in from here. There might be other things at play, but figured having a look at CI here would help narrow down where it might  be coming from.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Ah, it's as I suspected:

```
The following NEW packages will be INSTALLED:
...
dlib:             19.20-py38hbc70de2_1       conda-forge
...
lipo 1.2.1 requires dlib, which is not installed.
```

I'll go take a look over there...

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Hooray green! Thanks for the alley-oop!

**Review by jdb78 — APPROVED** [review]
Thanks a lot for this update!

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
